spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sphuta_freelancer?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update           # Automatically creates/updates schema (dev use only, avoid in prod)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true         # Pretty-print SQL in logs
    open-in-view: false          # Disable session-in-view for cleaner transaction boundaries
  mvc:
    format:
      date: iso                  # Enforces ISO date format for @DateTimeFormat

server:
  port: 8080                     # Application runs on http://localhost:8080

logging:
  level:
    root: INFO                   # Default log level
    org.hibernate.SQL: INFO      # Log SQL queries (DEBUG would show bind parameters too)

# Swagger / OpenAPI config
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs           # JSON/YAML spec served here
  swagger-ui:
    enabled: true
    path: /swagger-ui.html       # Swagger UI available at http://localhost:8080/swagger-ui.html
