spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sphuta_freelancer?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  mvc:
    problemdetails:
      enabled: true

logging:
  level:
    root: INFO
    net.sphuta.tms: DEBUG

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /v3/api-docs
