package net.sphuta.tms.freelancer.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.OffsetDateTime;

/**
 * ==========================================================
 * TmsClientEntity
 * ==========================================================
 *
 * JPA Entity representing the `clients` table.
 *
 * Purpose:
 * - Stores client details including company, contact info,
 *   billing preferences, and account status.
 * - Backed by MySQL with AUTO_INCREMENT primary key.
 *
 * Notes:
 * - {@code id} is auto-generated by the database.
 * - {@code createdAt} and {@code updatedAt} are system-managed via Hibernate.
 * - Index defined on {@code email} for fast lookups.
 */
@Getter
@Setter
@Entity
@Table(
        name = "clients",
        indexes = {
                @Index(name = "idx_client_email", columnList = "email")
        }
)
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ClientEntity {

    /** Primary key (AUTO_INCREMENT). */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)   // ✅ MySQL AUTO_INCREMENT
    @Column(name = "id", nullable = false, updatable = false)
    private Integer id;

    /** Company name (optional, max 255 chars). */
    @Column(name = "company_name", length = 255)
    private String companyName;

    /** Contact's first name (max 200 chars). */
    @Column(name = "first_name", length = 200)
    private String firstName;

    /** Contact's last name (max 200 chars). */
    @Column(name = "last_name", length = 200)
    private String lastName;

    /** Primary billing email (required, max 320 chars). */
    @Column(length = 320, nullable = false)
    private String email;

    /** Mobile phone (max 50 chars). */
    @Column(name = "mobile_phone", length = 50)
    private String mobilePhone;

    /** Business/office phone (max 50 chars). */
    @Column(name = "business_phone", length = 50)
    private String businessPhone;

    /** Address line 1 (stored as TEXT for flexibility). */
    @Column(name = "address_line1", columnDefinition = "TEXT")
    private String addressLine1;

    /** Address line 2 (stored as TEXT for flexibility). */
    @Column(name = "address_line2", columnDefinition = "TEXT")
    private String addressLine2;

    /** City (max 120 chars). */
    @Column(length = 120)
    private String city;

    /** State/Province (max 120 chars). */
    @Column(length = 120)
    private String state;

    /** Postal code (max 40 chars). */
    @Column(name = "postal_code", length = 40)
    private String postalCode;

    /** Country code (ISO-3166-1 alpha-2). */
    @Column(name = "country_code", length = 2)
    private String countryCode;

    /** Whether to send reminders to this client. */
    @Column(name = "send_reminders")
    private Boolean sendReminders;

    /** Whether to apply late fees to this client. */
    @Column(name = "charge_late_fees")
    private Boolean chargeLateFees;

    /** Late fee percent applied (0–100). */
    @Column(name = "late_fee_percent")
    private Double lateFeePercent;

    /** Currency code (ISO-4217, e.g., USD). */
    @Column(name = "currency_code", length = 3)
    private String currencyCode;

    /** Preferred language (e.g., en, en-US). */
    @Column(length = 16)
    private String language;

    /** Whether invoice attachments are allowed. */
    @Column(name = "allow_invoice_attachments")
    private Boolean allowInvoiceAttachments;

    /** Active flag (true=active, false=archived). */
    @Column(name = "is_active")
    private Boolean isActive;

    /** Timestamp when the record was first created (system-managed). */
    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private OffsetDateTime createdAt;

    /** Timestamp when the record was last updated (system-managed). */
    @UpdateTimestamp
    @Column(name = "updated_at")
    private OffsetDateTime updatedAt;
}
