package net.sphuta.tms.freelancer.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;

import java.time.OffsetDateTime;

/**
 * Data Transfer Object for Task.
 * Used for transferring task data between client and server.
 * Includes validation annotations.
 * Created and updated timestamps are read-only.
 * Project ID is required to associate task with a project.
 * Task name is required and cannot be blank.
 * Description is optional.
 * ID is read-only and generated by the system.
 * Timestamps are managed by the system.
 */
public record TaskDto(
        @JsonProperty(access = JsonProperty.Access.READ_ONLY)
        @Schema(description = "Task id", example = "101")
        Integer id,

        @Schema(description = "Project id this task belongs to", example = "5", required = true)
        Integer projectId,

        @NotBlank
        @Schema(description = "Task name/title", example = "Implement login UI", required = true)
        String taskName,

        @Schema(description = "Optional longer description", example = "Implement login screen with validation.")
        String description,

        @JsonProperty(access = JsonProperty.Access.READ_ONLY)
        OffsetDateTime createdDt,

        @JsonProperty(access = JsonProperty.Access.READ_ONLY)
        OffsetDateTime updatedDt
) {}
