package net.sphuta.tms.freelancer.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Builder;

import java.math.BigDecimal;

/**
 * ==========================================================
 * TmsEstimateItemDto
 * ==========================================================
 *
 * Unified DTO for estimate line items.
 *
 * Purpose:
 * - Used for both API requests (create/update) and responses (read).
 * - Enforces validation rules on input while exposing system-managed fields in responses.
 *
 * Notes:
 * - Keeps financial values as {@link BigDecimal} for precision.
 * - Nullable fields like `id` are read-only and ignored on input.
 */
@Builder(toBuilder = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
@Schema(name = "TmsEstimateItemDto", description = "Estimate line item DTO (for requests and responses)")
public record TmsEstimateItemDto(

        /** Unique identifier of the estimate item (system-managed, response only). */
        @Schema(description = "Item ID (auto-generated by system)", example = "501", accessMode = Schema.AccessMode.READ_ONLY)
        Integer id,

        /** Item description (required for request). */
        @NotBlank(message = "Item description is required")
        @Schema(description = "Description of the item or service", example = "Design work")
        String description,

        /** Quantity for this line item (must be > 0). */
        @NotNull(message = "Quantity is required")
        @DecimalMin(value = "0.01", message = "Quantity must be at least 0.01")
        @Schema(description = "Quantity for this item", example = "10.00")
        BigDecimal quantity,

        /** Unit price for this item (must be >= 0). */
        @NotNull(message = "Unit price is required")
        @DecimalMin(value = "0.00", message = "Unit price cannot be negative")
        @Schema(description = "Unit price for this item", example = "50.00")
        BigDecimal unitPrice
) {}
